trigger:
- feature-ms-alejandroAraya-mensaje

pool: 'mac'

steps:

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'devopsv3'
    organization: 'flodomiro'
    projectKey: 'flodomiro_microservicio-spring'
    projectName: 'microservicio-spring'